---

# Review & delete task
# - name: "Verify Data Model Has Required Device Information"
#   cisco.nac_dc_vxlan.dtc.add_device_check:
#     fabric_data: "{{ MD.fabric }}"
#   delegate_to: 127.0.0.1
#   run_once: true

- name: Set inv_file_name Var
  ansible.builtin.set_fact:
    inv_file_name: "{{ MD.fabric.global.name }}_inventory.yml"

- name: Set Path For Inventory File Lookup
  ansible.builtin.set_fact:
    inv_file_path: "{{ role_path }}/files/{{ inv_file_name }}"

- name: Build Fabric Switch Inventory List From Template
  ansible.builtin.template:
    src: ndfc_inventory.j2
    dest: "{{ inv_file_path }}"

- name: Create Empty inv_config Var
  ansible.builtin.set_fact:
    inv_config: null

- name: Set inv_config Var
  ansible.builtin.set_fact:
    inv_config: "{{ lookup('file', inv_file_name) | from_yaml }}"
  when: MD.fabric.topology.switches
